version: '3'
services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend:/app:ro
      - /app/node_modules
    environment:
      - MONGO_USER=test
      - MONGO_PASSWORD=test
      - SESSION_SECRET=secret
    
    command: npm run dev