version: '3'
services:
  nginx:
    ports:
      - "3000:80"
      
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend:/app:ro
      - /app/node_modules
    environment:
      - MONGO_USER=test
      - MONGO_PASSWORD=test
      - SESSION_SECRET=secret
    command: npm run dev

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev